services:
  backend:
    restart: unless-stopped
    build:
      context: .
      dockerfile: ./docker/backend/Dockerfile
    entrypoint: /app/docker/backend/entrypoint.sh
    command: [
        "sh",
        "-c",
        "uv pip install debugpy &&
        python -m debugpy --wait-for-client --listen 0.0.0.0:5678
        -m uvicorn server.asgi:application --host 0.0.0.0 --port 8000 --reload",
      ]
    working_dir: /app/backend
    depends_on:
      db:
        condition: service_healthy
      valkey:
        condition: service_healthy
    networks:
      - backend
    ports:
      - 8000:8000
      - 5678:5678
    expose:
      - 8000
    env_file:
      - ./.env
    develop:
      watch:
        - action: sync
          path: ./backend
          target: /app/backend
          ignore:
            - __pycache__/
            - "*.pyc"
        - action: sync
          path: ./example_app
          target: /app/example_app
          ignore:
            - __pycache__/
            - "*.pyc"
        - action: rebuild
          path: ./pyproject.toml

  celery-worker:
    restart: unless-stopped
    build:
      context: .
      dockerfile: ./docker/backend/Dockerfile
    command: celery -A server worker -l DEBUG --concurrency=1
    working_dir: /app/backend
    depends_on:
      db:
        condition: service_healthy
      valkey:
        condition: service_healthy
    networks:
      - backend
    env_file:
      - ./.env
    develop:
      watch:
        - action: sync
          path: ./backend
          target: /app/backend
          ignore:
            - __pycache__/
            - "*.pyc"
        - action: sync
          path: ./example_app
          target: /app/example_app
          ignore:
            - __pycache__/
            - "*.pyc"

  flower:
    restart: unless-stopped
    build:
      context: .
      dockerfile: ./docker/backend/Dockerfile
    command: celery -A server flower --port=5555
    working_dir: /app/backend
    depends_on:
      - celery-worker
    networks:
      - backend
    ports:
      - 5555:5555
    env_file:
      - ./.env

  db:
    image: postgres:18-alpine
    restart: always
    environment:
      - POSTGRES_USER=${DATABASE_USERNAME}
      - POSTGRES_PASSWORD=${DATABASE_PASSWORD}
      - POSTGRES_DB=${DATABASE_NAME}
    ports:
      - 5432:5432
    expose:
      - 5432
    volumes:
      - db:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5
    networks:
      - backend

  valkey:
    restart: unless-stopped
    image: valkey/valkey:9-alpine
    expose:
      - 6379
    ports:
      - 6379:6379
    volumes:
      - valkey_data:/data
    healthcheck:
      test: ["CMD", "valkey-cli", "ping"]
      interval: 5s
      timeout: 5s
      retries: 5
    networks:
      - backend

volumes:
  static_volume: {}
  db: {}
  valkey_data: {}

networks:
  backend:
    driver: bridge
